stages:
  - deploy
  - test

deploy:
  stage: deploy
  script:
    - echo "deploy"
  only:
    - master
  
test:
  stage: test
  script:
    - pylint3 -E dmx.py
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
    - ./test_dmx-py.sh
  only:
    - master


manual_test:
  stage: test
  script:
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
    - ./test_dmx-py.sh
  only:
    - master
  when: manual
