stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pylint3 -E dmx.py
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
    - ./test_dmx-py.sh
  only:
    - master
    - tags

manual_test:
  stage: test
  script:
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
    - ./test_dmx-py.sh
  only:
    - master
    - tags
  when: manual

copy_to_ci:
  stage: deploy
  script:
    - CIDIR='/var/www/download.dmx.systems/ci'
    - DESTDIR="${CIDIR}/${CI_PROJECT_NAME}"
    - NUNC="$( date +%F )"
    - DESTZIPFILE="${CI_PROJECT_NAME}_${NUNC}_${CI_PIPELINE_ID}.zip"
    - if [ ! -d  ${DESTDIR} ]; then mkdir ${DESTDIR}; fi
    - zip "${CI_PROJECT_NAME}.zip" * -x "*/.*"
    - mv "${CI_PROJECT_NAME}.zip" ${DESTDIR}/${DESTZIPFILE}  
  only:
    - master
