stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pylint3 -E dmx.py
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
    - ./test_dmx-py.sh
  only:
    - master
    - tags

manual_test:
  stage: test
  script:
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
    - ./test_dmx-py.sh
  only:
    - master
    - tags
  when: manual

copy_to_ci:
  stage: deploy
  script:
    - zip "target/${CI_PROJECT_NAME}.zip" * -x "*/.*"
  artifacts:
    paths: 
      - target/*.zip
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
  only:
    - master
