stages:
  - deploy
  - test

deploy:
  stage: deploy
  script:
    - echo "create config file"
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/server\ \=\ ${TESTHOST}/g" dmx.cfg
  only:
    - master
  
test:
  stage: test
  script:
    - ./test_dmx-py.sh
  only:
    - master
