stages:
  - deploy
  - test

deploy:
  - stage: deploy
  - echo "create config file"
  - cp dmx.cfg.example dmx.cfg
  - echo "change config file"
  - cat dmx.cfg
  
test:
  - stage: test
  - echo "test"