stages:
  - deploy
  - test

deploy:
  stage: deploy
  script:
    - echo "create config file"
    - cp dmx.cfg.example dmx.cfg
    - echo "change config file"
    - sed -i "s/^server\ \=\ localhost/^server\ \=\ ${TESTHOST}" dmx.cfg
    - cat dmx.cfg
  only:
    - master
  
test:
  stage: test
  script:
    - echo "test"
  only:
    - master
